src/ui/settingsdialog.cpp

Trying to fix #250, not sure if this works, though :)

set User-Agent for HTTP downloads

---

README.md

Our main screenshot is a bit dated now (and I vaguely remember some people complaining it's ugly). This adds a new screenshot made today. :)
See also zealdocs/zealdocs.github.io#4 for update at zealdocs.org
Preview at github.com:

doc: New screenshot for README.md

---

src/ui/forms/settingsdialog.ui
src/ui/settingsdialog.cpp
src/ui/settingsdialog.h

Makes browsing through the list of downloadable docsets easier.

Adds an input bar for filtering available docsets

---

src/ui/mainwindow.cpp

Update completions in search box whenever a docset is installed or
removed.

ui: Update completions on docset add (fixes #478)

---

src/registry/searchmodel.cpp
src/registry/searchmodel.h
src/ui/mainwindow.cpp

Fix issue #436 by
- Implement removeRows function for SearchModel
- Remove all items in SearchModel for active tab after removing corresponding docset.

Fix issue 436

---

src/core/settings.cpp
src/core/settings.h
src/ui/forms/settingsdialog.ui
src/ui/mainwindow.cpp
src/ui/settingsdialog.cpp

In addition to previous PR, this feature is good usability enhancement, for me at least. I don't know your personal point of view on it, but maybe you can find it useful.

Implemented opening new tab after current one

---

src/ui/mainwindow.cpp
src/ui/mainwindow.h

Closes #524 
Maybe any remarks?

Added duplicate tab feature

---

src/libs/ui/docsetsdialog.cpp

Docsets need to be removed from registry first, to avoid rename() failing when files are in use.

ui: Fix docset removing on Windows (fixes #621)

---

src/app/app.pro
src/app/main.cpp
src/libs/registry/docset.cpp
src/libs/registry/docset.h
src/libs/registry/registry.pro
src/libs/util/sqlitedatabase.cpp
src/libs/util/sqlitedatabase.h
src/libs/util/util.pri

This is going to help with implementing PR #614 in a cleaner way, avoiding problems with sqlite3_create_function interface availability on various platforms.

registry: Add our own sqlite3 wrapper

---

src/libs/registry/docset.cpp
src/libs/registry/searchresult.h
src/libs/util/sqlitedatabase.cpp
src/libs/util/sqlitedatabase.h

(Accidentally, adds fuzzy search too.)
Uses an O(m+n) algorithm based on https://github.com/bevacqua/fuzzysearch - should be faster than the one initially proposed in PR #281.
Screenshots:

Better sorting of search results (fixes #100 and #603)

---

src/libs/registry/docset.cpp

An attempt to make it a bit cleaner, and, hopefully, more efficient. I have a few more optimizations in mind, but let's start with these.
Please give this a look, and maybe some testing/benchmarking.

registry: Cleanup fuzzy search code, and optimize a bit

---

src/libs/registry/docset.cpp

registry: Prioritize exact matches over fuzzy

---

src/libs/registry/docset.cpp

Fixes 2 search cases not matching with fuzzy search:
1. "**ad**darg" not matching  "**a**rgparse.ArgumentParser.a**d**d_argument" in the Python docset,
2. "**te**strle" not matching "AWS.Elas**t**icTranscod**e**r.testRole" in the AWS JS docset.
Both were due to the 2nd char of needle being more than 8 chars from 1st match of 1st needle char in haystack (highlighted with **bold** above). Adding a simple recursive call to retry matching from 2nd match of 1st char fixes both cases.
It is slightly slower now - my simple performance test case of [all 2M symbols from all docsets](https://github.com/jkozera/zeal/blob/c30da109e8624b961e7b94f3f59f783b188c0d91/tests/py_unit/testscoring_build.py#L35) indicates about 20% slow down, from 1.2 seconds to 1.45 seconds on my box, on the "aaaaaaaaaa" query …

registry: Add more exhaustive search for fuzzy matching

---

src/libs/ui/mainwindow.cpp
src/libs/ui/mainwindow.h

Hi, 
I make tabs are movable as default.
Thanks.

ui: movable tabs

---

src/libs/ui/mainwindow.cpp

Just add other way to create new tab -> double click on the empty area of tab bar.

ui: Create new tab on tabbar doubleclick

---

src/libs/registry/docset.cpp
src/libs/registry/docset.h
src/libs/ui/docsetsdialog.cpp
src/libs/ui/docsetsdialog.h

This implements a simple mechanism for updating user-added docs feeds.

registry,ui: Feed updates (issue #289)

---

src/libs/ui/mainwindow.cpp
src/libs/ui/mainwindow.h
src/libs/ui/mainwindow.ui
src/libs/ui/widgets/webview.cpp
src/libs/ui/widgets/webviewtab.cpp
src/libs/ui/widgets/webviewtab.h

This change stops practice of sharing a single web view between tabs.

ui: Use one web view per tab

---

src/libs/ui/mainwindow.cpp

This is a fix for the problem mentioned in https://github.com/zealdocs/zeal/issues/888

Fix preferences hotkey

---

src/libs/ui/aboutdialog.ui

fixed typo, missing character

---

README.md

As mentioned in #924, making it more visible in the Readme which was not done yet due to time constraints. The picture used for the badge is from one of the badge styles they offer for embedding into html-based forums.

Add text, shield, link to buymeacoffee

---

.github/workflows/appimage/Dockerfile
pkg/appimage/appimage-amd64.yml

Fix missing symbol on system fontconfig for AppImage package

build(appimage): add dependencies, disable Qt WebEngine sandbox

---

.github/workflows/appimage/Dockerfile

build(appimage): pin appimage-builder to v0.8.3

---

.github/workflows/build-check.yml
CMakePresets.json
vcpkg.json

build(cmake): add CMakePresets.json

---

.github/workflows/build-check.yml
CMakeLists.txt
assets/freedesktop/CMakeLists.txt
src/app/CMakeLists.txt
src/app/main.cpp
src/libs/browser/CMakeLists.txt
src/libs/browser/webview.cpp
src/libs/core/CMakeLists.txt
src/libs/core/settings.cpp
src/libs/registry/CMakeLists.txt
src/libs/registry/docset.cpp
src/libs/registry/docsetregistry.cpp
src/libs/registry/docsetregistry.h
src/libs/registry/listmodel.cpp
src/libs/sidebar/CMakeLists.txt
src/libs/ui/CMakeLists.txt
src/libs/ui/docsetsdialog.cpp
src/libs/ui/mainwindow.cpp
src/libs/ui/qxtglobalshortcut/CMakeLists.txt
src/libs/ui/qxtglobalshortcut/qxtglobalshortcut.cpp
src/libs/ui/qxtglobalshortcut/qxtglobalshortcut_mac.cpp
src/libs/ui/qxtglobalshortcut/qxtglobalshortcut_p.h
src/libs/ui/qxtglobalshortcut/qxtglobalshortcut_win.cpp
src/libs/ui/qxtglobalshortcut/qxtglobalshortcut_x11.cpp
src/libs/ui/settingsdialog.cpp
src/libs/ui/settingsdialog.h
src/libs/ui/settingsdialog.ui
src/libs/ui/widgets/CMakeLists.txt
src/libs/util/CMakeLists.txt
src/libs/util/sqlitedatabase.cpp

Adds support for Qt 6 along with preserving option to build with Qt 5.

feat: add Qt 6 support

---

src/libs/ui/mainwindow.cpp
src/libs/ui/mainwindow.ui
src/libs/ui/settingsdialog.ui

It provides correct semantics and better accessibility.

fix(ui): use Unicode ellipsis instead of triple-dot

---

src/libs/browser/searchtoolbar.cpp

feat(browser): add Ctrl+Enter shortcut for Highlight All option

---

README.md

This matches the "or later" clause in the About dialog of Zeal and in the appdata.xml file

README.md: update license to GPLv3 or later
