- src/core/application.cpp
- src/ui/mainwindow.cpp
- src/ui/settingsdialog.cpp
Because on MSVC Qt uses wchar_t, QStringLiteral can only be applied on one constant string at a time.
> MSVC Fixes

- src/ui/mainwindow.cpp
this fix the problem of losing focus instantly when typing
> ui: Prevent QWebEnginePage from stealing focus from the search input

- src/ui/mainwindow.cpp
Fix an incomplete rename causing a compiler error.
> ui: Fix rename tocView to tocListView

- qmake/common.pri
- src/libs/ui/ui.pri
Missing USE_APPINDICATOR in libs/core/ was causing the MainWindow class declaration to be truncated, thus causing memory corruption when later used with the full definition in libs/ui/.
> Fix appindicator crashes

- src/libs/core/application.cpp
- src/libs/core/networkaccessmanager.cpp
- src/libs/core/networkaccessmanager.h
This change adds back a custom network access manager, that was removed
as a fix for #474. Although this time the URL validation logic is much
more simple.
> core: Reject no-scheme URLs on a local file system (fixes #532)

- src/libs/ui/docsetsdialog.cpp
This fixes duplicated items in selection models because of multiple
columns.
> ui: Fix 'Select All' selection in the docset manager

- src/libs/ui/mainwindow.cpp
If HTML page doesn't set background ("Bash" docset for example) then it will be theme-dependent. When light theme is used with disabled dark mode everything works well - we have black text on white background. When light theme is used with enabled dark mode everything is fine again - we have light text on dark background. But when dark theme is used with disabled dark mode we will see black text on dark background (tested on Qt 5.11). Therefore when our dark mode CSS is applied we will see light text on light background :( So we should always set default background color to white - it will be properly processed both for light and dark themes.
OLD version:
NEW version:
> Background fix for dark mode

- src/libs/registry/docset.cpp
- src/libs/registry/docset.h
- src/libs/ui/mainwindow.cpp
- src/libs/ui/widgets/webviewtab.cpp
- src/libs/ui/widgets/webviewtab.h
Follow up to https://github.com/zealdocs/zeal/issues/999
Implement `isJavaScriptEnabled` through `Info.plist`
> Enable JavaScript only when Info.plist specifies isJavaScriptEnabled

- src/libs/ui/widgets/searchtoolbar.cpp
`QAction::triggered` has the prototype `triggered(bool checked=false)`
`QAbstractButton::animateClick` has the prototype `nimateClick(int msec=100)`
In this case, we don't set the QAction checkable boolean and its by default, `false`.
An implicit conversion of `false` to `int` occurs here. The actual signal to slot connection is also confirmed using GammaRay
> Investigate TODO: QAction triggered signal doesn't connect with QToolButton animateClick slot

- src/libs/ui/mainwindow.cpp
- src/libs/ui/widgets/webviewtab.cpp
- src/libs/ui/widgets/webviewtab.h
Fixes #767: if needed ctrl+= is easy to add
It really helps when using a touchpad ;)
> Add zoom shortcuts ctrl + (+-0)

- src/libs/ui/docsetsdialog.cpp
Sometimes, when copying a feed URL, I accidentally include a leading
whitespace. Zeal then denies the URL since it does not start with a
valid protocol indicator.
This PR trims the feed URL before using it. This might improve the UX
for some users.
> Trim feed URL before trying to resolve it

- src/libs/ui/docsetsdialog.cpp
- src/libs/ui/mainwindow.cpp
- src/libs/ui/qxtglobalshortcut/qxtglobalshortcut.cpp
- src/libs/ui/qxtglobalshortcut/qxtglobalshortcut_p.h
[According to the Qt docs](https://doc.qt.io/qt-5/qtglobal.html#Q_OS_OSX), the `Q_OS_OSX` macro is deprecated and
`Q_OS_MACOS` should be used instead.
I ran a mixture of `find` and `sed` over the `src/` folder to replace all occurrences.
Not a big deal after all, but I thought it was a fair change.
> Replace Q_OS_OSX with Q_OS_MACOS

- src/libs/registry/docset.cpp
- src/libs/registry/docset.h
- src/libs/registry/docsetregistry.cpp
- src/libs/registry/listmodel.cpp
- src/libs/registry/searchquery.cpp
- src/libs/registry/searchquery.h
Qt containers return a deep copy when used in a loop with a call to a member function such as [`QMap::keys()`](https://doc.qt.io/qt-5/qmap.html#keys) or [`QMap::values(const Key& key)`](https://doc.qt.io/qt-5/qmap.html#values-1).
Using iterators or assigning the return value to a const object avoids the copy, thanks to the implicit sharing feature of Qt.
See the code examples [here](https://doc.qt.io/qt-5/qtglobal.html#qAsConst).
Further, when arguments in a constructor are to be passed to a member's constructor, taking the argument by value and then moving it can be beneficial when the argument is an rvalue as it will avoid the call to a copy constructor, thanks to move semantics.
See [here](https://clang.llvm.org/extra/clang-tidy/checks/modernize-pass-by-value.html).
> Avoid creation of unnecessary objects

- src/libs/browser/webview.cpp
- src/libs/browser/webview.h
Control zoom factor directly rather than using hardcoded zoom levels.
In order to ensure that the webview starts out scaled appropriately to the
current font DPI, we set default zoom level based on current DPI, e.g.:
96 DPI - 100% zoom
120 DPI - 125% zoom
Since this will allow zoom levels beyond the predefined set, I also change the
logic for zooming to simply add or remove 10% to the current scaling.
Note that if we want to still maintain the predefined zoom levels, I can rewrite this to multiply the predefined zoom levels by the zoom level derived from the current DPI.
> Set default zoom of webview based on DPI.

- src/app/main.cpp
Wayland uses the .desktop file to find the app icon. Without it being specified the correct icon is not shown. 
Tested on Gnome/Wayland.
References:
* https://community.kde.org/Guidelines_and_HOWTOs/Wayland_Porting_Notes#Application_Icon
* https://doc.qt.io/qt-5/qguiapplication.html#desktopFileName-prop
> Fix missing app icon on Wayland

- src/libs/ui/widgets/searchedit.cpp
Before: 
After: 
Test carried out under KDE, with a scaling factor of 2.
Note that I did not really test how it behaves on a normal DPI screen or multiple screens with different DPI, because of lack of devices.
> fix(ui): correctly position search completer label on HiDPI display

- src/libs/core/extractor.cpp
- src/libs/ui/searchitemdelegate.cpp
- src/libs/ui/widgets/searchedit.cpp
Building on my Arch Linux box with Qt 5.13.1 installed showed a few warnings saying that the `QFontMetrics::width()` and `QDir::operator=(const QString&)` were deprecated. I replaced them with the new alternatives and wrapped them with a compile-time check, which wasn't needed for `QDir::operator=(const QDir&)`. Now it should compile cleanly.
Since I saw you already made a very similar fix, by skimming through the log, I reused the same commit message of that old commit.
> Fix Qt 5.11 deprecation warning for QFontMetrics::width

- src/libs/ui/docsetsdialog.cpp
- src/libs/ui/docsetsdialog.ui
When the user modifies the docsets directory from the settings page, the docsets page shows `Docset storage is read-only` when the actual source of the error is that the directory does not exist on the file system. This PR fixes that by making the label show the correct error message based on the actual error.
> Improve error message when storage does not exist

- src/libs/browser/webview.cpp
- src/libs/core/application.cpp
- src/libs/core/settings.cpp
- src/libs/registry/docset.cpp
- src/libs/sidebar/container.cpp
- src/libs/sidebar/proxyview.cpp
- src/libs/sidebar/proxyview.h
- src/libs/ui/browsertab.cpp
- src/libs/ui/docsetsdialog.cpp
- src/libs/ui/mainwindow.cpp
- src/libs/ui/qxtglobalshortcut/qxtglobalshortcut_p.h
- src/libs/ui/qxtglobalshortcut/qxtglobalshortcut_x11.cpp
- src/libs/ui/settingsdialog.cpp
- src/libs/ui/widgets/searchedit.cpp
I ran the code base through the `modernize-*` checks of clang-tidy.
Enhancements include the use of `auto` in order to avoid repeating the type name when obvious from the context, the use of `constexpr` for array literals and usage of move semantics to avoid unnecessary copies.
> Modernize code base with clang-tidy's modernize-*

- src/app/resources/browser/404.html
- src/app/resources/browser/welcome.html
Twitter links were broken due to a typo (`twiter` instead of `twitter`).
This pull request fixes the links.
This fixes https://github.com/zealdocs/zeal/issues/1207
> Fix broken twitter links in 404.html, welcome.html

- .appveyor.yml
- .github/workflows/build-check.yml
- README.md
- pkg/appimage/appimage-amd64.yml
- src/app/resources/browser/404.html
- src/app/resources/browser/assets/css/darkmode.css
- src/app/resources/browser/welcome.html
- src/libs/browser/CMakeLists.txt
- src/libs/browser/searchtoolbar.cpp
- src/libs/browser/searchtoolbar.h
- src/libs/browser/urlrequestinterceptor.cpp
- src/libs/browser/urlrequestinterceptor.h
- src/libs/browser/webcontrol.cpp
- src/libs/browser/webcontrol.h
- src/libs/browser/webpage.cpp
- src/libs/browser/webpage.h
- src/libs/browser/webview.cpp
- src/libs/browser/webview.h
- src/libs/core/CMakeLists.txt
- src/libs/core/settings.cpp
- src/libs/ui/CMakeLists.txt
- src/libs/ui/browsertab.cpp
- src/libs/ui/mainwindow.cpp
- src/libs/ui/settingsdialog.cpp
Porting from the obsolete QWebKit to the QWebEngine. Most features should work with it (QWebEngine does not have all features like QWebKit).
In addition, this modification blocks requests from local pages to web pages. Some documentation sets track the user with Google Analytics, this is now blocked.
> feat(browser,ui): port to Qt WebEngine

- src/libs/sidebar/CMakeLists.txt
Fixes unresolved soname dependency after install.
> build(sidebar): add missing STATIC keyword

- assets/freedesktop/org.zealdocs.Zeal.desktop
Currently, Zeal has a problem with duplicating the application icon when opening the application in Linux GNOME environment.
Exact the same problem in the following link.
https://askubuntu.com/questions/975178/duplicate-application-icons-in-ubuntu-dock-upon-launch
In order to solve this problem, we need to specify `StartupWMClass=Zeal` in `org.zealdocs.Zeal.desktop`
> fix(assets): prevent duplicating application icons in GNOME dock

- src/libs/core/networkaccessmanager.cpp
QNetworkRequest::FollowRedirectsAttribute is deprecated.
> fix(core): use QNetworkRequest::RedirectPolicyAttribute

- src/libs/core/networkaccessmanager.cpp
On Fedora 34, I've built Zeal with Qt5.15.2 and OpenSSL-1.1.1l.
When trying to check for updates, the request fails with "SSL handshake error". I can also reproduce this issue in one of the [Qt examples](https://code.qt.io/cgit/qt/qtbase.git/tree/examples/network/http?h=5.15), which includes the more descriptive message "The issuer certificate of a locally looked up certificate could not be found".
The root cause seems to be the same as described in [another issue](https://github.com/owncloud/client/issues/1540): If I run `strace` on `zeal`, I confirm that it doesn't access my certificate bundle (`/etc/pki/tls/certs/ca-bundle.crt`), instead it tries to lookup `c_rehash` generated files that aren't present.
Regardless of which files are present, Zeal can be resilient to these cases and …
> fix: Include system CA certificates in requests

- src/libs/browser/webview.cpp
Version on master doesn't let me enter search with pauses or switch among results. Browser takes the focus away from the search box each time it's updated.
Happens since 5360da3d7f34906ff41c10ac74e6b01636598903.
> fix(browser): prevent WebEngine taking away focus from searchbox

- .gitignore
Hi for my personal builds I added a couple of presets to the `CMakeUserPresets.json` file which is not meant to be commited so I can build with MSVC on Windows.
These are the presets that I'm using (VS Code does not enable the MSVC compiler unless you define the toolset and architecture values):
```json
{
"name": "MSVC",
"displayName": "MSVC",
"description": "Use the Visual Studio compiler",
"cacheVariables": {
"CMAKE_CXX_COMPILER": "cl",
"CMAKE_C_COMPILER": "cl"
},
"architecture": {
"value": "x64",
"strategy": "external"
},
"toolset": {
"value": "host=x64",
"strategy": "external"
}
},
{
"name": "ninja-multi-vcpkg-MSVC",
"displayName": "UVCPKG",
"description": "Use the Visual Studio compiler",
"inherits": ["ninja-multi-vcpkg", "MSVC"]
}
```
> chore(gitignore): add CMakeUserPresets.json

- vcpkg.json
previous schema link does not exist anymore
> build(vcpkg): update schema link

- src/libs/ui/docsetlistitemdelegate.cpp
- src/libs/ui/searchitemdelegate.cpp
> fix(ui): fix RTL layout in list delegates

- src/libs/ui/mainwindow.cpp
Qt internally can not de-duplicate standard shortcuts like QKeySequence::NextChild and manually specified Ctrl+PageDown which are practically the same thing on default KDE/Plasma installations.
Fixes #1465
> fix(ui): replace QKeySequence::NextChild with manual shortcut

- .gitignore
Some people build zeal with local installed vcpkg. vcpkg will build dependencies into vcpkg_installed folder.
> chore(gitignore): add vcpkg and vcpkg_install directory

- src/libs/browser/settings.cpp
- src/libs/core/settings.cpp
- src/libs/core/settings.h
- src/libs/ui/settingsdialog.cpp
- src/libs/ui/settingsdialog.ui
Switch to Chromium's dark mode instead of CSS hacks. More information is available in [QTBUG-72028](https://bugreports.qt.io/browse/QTBUG-72028). By default Zeal will try to follow system's color mode.
CSS hack is kept around for builds with Qt version lower than 5.12 (hi, Ubuntu 20.04), and will be removed in one of the future releases.  
Currently there's no way to enable dark mode without restart. See [QTBUG-84484](https://bugreports.qt.io/browse/QTBUG-84484).
> feat(browser): use native Chromium dark mode

- src/app/main.cpp
This enables dark mode support.
Fixes #811.
> feat(ui): use Fusion style on Windows 10 & 11

- src/libs/registry/docset.cpp
- src/libs/registry/docsetmetadata.cpp
- src/libs/registry/docsetregistry.cpp
- src/libs/ui/docsetsdialog.cpp
- src/libs/ui/qxtglobalshortcut/qxtglobalshortcut_x11.cpp
Reference: https://github.com/qt/qtbase/blob/v6.6.0/src/corelib/global/qttypetraits.h#L32
Tested building with qt 6.6.0, 6.5.3 and 5.15.10
> treewide: replace deprecated qAsConst with std::as_const()

- .github/workflows/build-check.yaml
- assets/freedesktop/org.zealdocs.zeal.appdata.xml.in
- pkg/appimage/appimage-amd64.yaml
This PR mainly introduces a handful of minor changes to the Linux AppStream metadata file:
- Replace the Windows screenshot by one taken on Linux
- Add link to release notes, which can be shown on Linux app stores, such as Flathub
- Simplify the content rating ([OARS](https://hughsie.github.io/oars/generate.html)) section
- Validate the Linux AppStream metadata file using GitHub Actions
> linux: minor appdata-related changes

- .github/workflows/build-check.yaml
- assets/freedesktop/org.zealdocs.zeal.appdata.xml.in
- pkg/appimage/appimage-amd64.yaml
These changes are mostly relevant for Flathub, as they've recently [transitioned](https://docs.flathub.org/blog/improved-build-validation/) to a more modern AppStream metadata validation tool, and this PR aims to abide to these new validation rules.
> linux: more appdata-related changes

- src/libs/core/CMakeLists.txt
For the issue https://github.com/zealdocs/zeal/issues/1602 .
Previously PR was https://github.com/zealdocs/zeal/pull/1607.
> build(cmake): find libarchive from brew on macos

- CMakeLists.txt
- src/libs/ui/aboutdialog.ui
Just tried this v0.7.1 . This PR fix copyright year in CMakeLists.txt and UI's about page:
> chore(cmake,ui): update copyright year

- src/app/CMakeLists.txt
Fixes #1643.
Starting from Qt 6.7.2 it is necessary to list all necessary components for Qt6 rather than deferring them. This commit fixes a build failure when cmake configures a build against Qt >= 6.7.2, where we otherwise see a failure like:
```
[   14s] CMake Error at
/usr/lib64/cmake/Qt6/QtPublicWalkLibsHelpers.cmake:259 (message):
[   14s]   The Concurrent target is mentioned as a dependency for
Registry, but not
[   14s]   declared.
[   14s] Call Stack (most recent call first):
[   14s]   /usr/lib64/cmake/Qt6/QtPublicWalkLibsHelpers.cmake:228
(__qt_internal_walk_libs)
[   14s]   /usr/lib64/cmake/Qt6/QtPublicWalkLibsHelpers.cmake:311
(__qt_internal_walk_libs)
[   14s]   /usr/lib64/cmake/Qt6Core/Qt6CoreMacros.cmake:651
(__qt_internal_collect_all_target_dependencies)
[   14s] …
```
> build(app): add missing Qt components to find_package

- .github/workflows/build-check.yaml
- .github/workflows/release.yaml
GitHub Actions no longer support Ubuntu 20.04.
> ci(github): stop building on Ubuntu 20.04
